osx_image: xcode8.3
sudo: required

language: node_js
node_js:
  - 7

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - PLATFORM=linux
    - os: osx
      env:
        - PLATFORM=mac
#        - CSC_LINK=$MAC_CSC_LINK
#        - CSC_KEY_PASSWORD=$MAC_CSC_KEY_PASSWORD

cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache
    - .electron-cache

install:
  - npm config set progress=false
  - npm config set spin=false
  - npm install

before_deploy:
  - npm run build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      npm run electron:build:mac;
    else
      npm run electron:build:linux;
    fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file:
    - release/**/*.dmg
    - release/**/*.AppImage
    - release/**/*.deb

after_deploy:
  - "echo 'Deploy successful, go get some sleep.'"

branches:
  only:
    - master
