osx_image: xcode8.3

sudo: required
dist: trusty

language: node_js

node_js:
  - 7

matrix:
  include:
    - os: linux
      dist: trusty
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
      env:
        - PLATFORM=linux
    - os: osx
      env:
        - PLATFORM=mac
#        - CSC_LINK=$MAC_CSC_LINK
#        - CSC_KEY_PASSWORD=$MAC_CSC_KEY_PASSWORD

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils

before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi

install:
- npm install

before_deploy:
- npm run release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file:
    - release/**/*.zip
    - release/**/*.deb
    - release/**/*.tar.gz
    - release/**/*.dmg
#  on:
#      tags: true

branches:
  only:
  - master
