os: unstable

version: '{build}'

environment:
  nodejs_version: 7
#  CSC_LINK: '%WINDOWS_CSC_LINK%'
#  CSC_KEY_PASSWORD: '%WINDOWS_CSC_KEY_PASSWORD%'

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

shallow_clone: true

clone_depth: 1

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - npm config set progress=false
  - npm config set spin=false
  - npm install

test: off
build: off

skip_non_tags: false

branches:
  only:
    - master

before_deploy:
  - npm run release

deploy:
  description: 'Deployed release binaries by Travis CI and AppVeyor'
  provider: GitHub
  auth_token:
    secure: 33YFa7Si4BBeojw89zyjXle6jXa2D559TygsIJzNsCGKyGqJmiwKQF3OXY2Ts6ok
  artifact: '**\*.exe'
  draft: false
  prerelease: false
  on:
    branch: master
#    appveyor_repo_tag: true

