platform:
  - x64

skip_tags: true

os: unstable

version: '{build}'

environment:
  nodejs_version: 7
  package_json_version: '1.0.0'
#  CSC_LINK: '%WINDOWS_CSC_LINK%'
#  CSC_KEY_PASSWORD: '%WINDOWS_CSC_KEY_PASSWORD%'

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'
  - '.electron-cache'

init:
  - git config --global core.autocrlf input

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Set-AppveyorBuildVariable "package_json_version" "$env:package_version"
  - set PATH=%APPDATA%\npm;%PATH%
  - npm config set progress=false
  - npm config set spin=false
  - npm install
  - npm run build
  - npm run electron:build:win

test: off
build: off

branches:
  only:
    - master

artifacts:
  - path: release\*.exe

deploy:
  provider: GitHub
  description: 'Deployed release binaries by Travis CI and AppVeyor'
  auth_token:
    secure: 33YFa7Si4BBeojw89zyjXle6jXa2D559TygsIJzNsCGKyGqJmiwKQF3OXY2Ts6ok
  artifact:
  release: $package_json_version
  force_update: true
  draft: false
  prerelease: false
  on:
    branch: master
